"""
Write the Cue rev A dev board schematic (KiCad 7 .kicad_sch) from devboard_circuit.py.

    python3 make_schematic.py      # writes cue_devboard.kicad_sch (+ .kicad_pro if missing)

One A2 sheet, five blocks (Power, Radio, Sensors, Haptics, Headers & test). Passives use the
stock KiCad Device/Switch/Connector symbols; ICs and connectors are drawn as pin boxes with
real pin names where the datasheet gives them. Every pin connects through a net label, so the
schematic is generated from - and checked against - the same pad-level netlist as the PCB.
"""
import os
import re
import uuid

import devboard_circuit as C

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "cue_devboard.kicad_sch")
SYMDIR = "/usr/share/kicad/symbols"
NS = uuid.UUID("6f1d3c2e-8a4b-4c1e-9d2f-5b7a6c3e1f00")
ROOT = str(uuid.uuid5(NS, "root"))
G = 2.54


def uid(*k):
    return str(uuid.uuid5(NS, "/".join(map(str, k))))


def snap(v, g=G):
    return round(v / g) * g


# ------------------------------------------------------------------ pin names from datasheets
NPM1300 = {
    "1": "VOUT1", "2": "PVSS1", "3": "SW1", "4": "PVDD", "5": "SW2", "6": "PVSS2", "7": "GPIO0", "8": "GPIO1",
    "9": "GPIO2", "10": "GPIO3", "11": "GPIO4", "12": "VDDIO", "13": "SDA", "14": "SCL", "15": "SHPHLD",
    "16": "VSET2", "17": "VSET1", "18": "NTC", "19": "VBAT", "20": "VSYS", "21": "VBUS", "22": "VBUSOUT",
    "23": "CC1", "24": "CC2", "25": "LED0", "26": "LED1", "27": "LED2", "28": "LSIN1", "29": "LSOUT1",
    "30": "LSIN2", "31": "LSOUT2", "32": "VOUT2", "33": "AVSS(EP)",
}  # nPM1300 PS v1.2.1, QFN32 pin assignments
DRV2605L = {"1": "REG", "2": "SCL", "3": "SDA", "4": "IN/TRIG", "5": "EN", "6": "VDD/NC", "7": "OUT+",
            "8": "GND", "9": "OUT-", "10": "VDD"}  # TI DRV2605L DGS pinout
T5838 = {"1": "DATA", "2": "GND", "3": "SELECT", "4": "WAKE", "5": "THSEL", "6": "CLK", "7": "VDD"}


def u1_names():
    """BL54L15 pad -> name (Ezurio BL54L10/BL54L15 datasheet pin-out)."""
    return {"8": "P2.02", "9": "P2.00", "10": "P2.01", "14": "P1.03", "17": "P0.00", "18": "P0.01", "20": "P1.07",
            "21": "P1.06", "22": "P1.05", "23": "P1.04", "28": "P1.10", "30": "P1.08", "32": "P1.14", "33": "P1.13",
            "35": "P1.11", "26": "VDD_nRF", "5": "SWDIO", "6": "SWDCLK", "7": "nRESET"}


NAMES = {"U1": u1_names(), "U2": NPM1300, "U5": DRV2605L, "U4": T5838}

# left / right pin order for the big parts (pads); anything not listed goes on the right
SIDES = {
    "U2": (["21", "23", "24", "19", "18", "15", "17", "16", "12", "13", "14", "7", "8", "9", "10", "11"],
           ["20", "4", "22", "3", "1", "5", "32", "28", "29", "30", "31", "25", "26", "27", "2", "6", "33"]),
    "U5": (["10", "6", "5", "4", "2", "3"], ["7", "9", "1", "8"]),
    "U4": (["7", "6", "1", "3"], ["4", "5", "2"]),
}

# ------------------------------------------------------------------ blocks
BLOCKS = [
    ("POWER - USB-C, nPM1300 (PS v1.2.1 Config 1), battery",
     ["J1", "D1", "C1", "C2", "U2", "C3", "RT1", "J2", "C4", "C5", "C20", "C21", "C17", "L1", "C6", "C18",
      "L2", "C7", "R3", "R4", "C19", "C22", "R1", "R2", "SW2"]),
    ("RADIO - Ezurio BL54L15 453-00044 (nRF54L15, MHF4 antenna connector)",
     ["U1", "C16", "R7", "R8", "J4", "SW1"]),
    ("SENSORS - T5838 mic, LSM6DSV16BX bone conduction + touch",
     ["U4", "C10", "U3", "C8", "C9", "R6", "E1"]),
    ("HAPTICS - DRV2605L + LRA", ["U5", "C11", "C12", "J3"]),
    ("HEADERS AND TEST POINTS",
     ["J5"] + [f"TP{i}" for i in range(1, 11)] + ["FID1", "FID2", "FID3"]),
]
NOTES = [
    "NOTES",
    "R7-R8: the cuff's BL54L15u Note 7 (P1.09-P1.12 < 1 MHz behind >=330 R), kept so both boards share one pin map.",
    "U1 antenna: plug a 2.4 GHz MHF4 antenna (Ezurio mFlexPIFA EFA2400A3S-10MH4L) into the module.",
    "J5 takes the V2S200D eval board: PDM left channel (T5838 is right).",
    "Generated by make_schematic.py from devboard_circuit.py - edit the circuit file, not this sheet.",
    "OPEN: nPM1300 TWI DC input limits (not tabulated in PS v1.2.1); bench-check I2C low level at 400 kHz.",
    "OPEN: shared PDM bus - T5838 right channel (SELECT=GND), external V2S200D on J5 must select left.",
    "Firmware: charger off at reset; select the 10k NTC (ADCNTCRSEL) and 32 mA before enabling charging.",
    "Firmware: LOADSW1 (MIC_1V8) off at reset - enable only after BUCK1 is confirmed at 1.8 V.",
]


# ------------------------------------------------------------------ library symbol extraction
def lib_symbol(lib, name):
    text = open(os.path.join(SYMDIR, lib + ".kicad_sym")).read()
    i = text.index(f'\n  (symbol "{name}"')
    depth, j = 0, i + 1
    while True:
        ch = text[j]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                break
        j += 1
    body = text[i + 1:j + 1]
    body = body.replace(f'(symbol "{name}"', f'(symbol "{lib}:{name}"', 1)
    pins = {}
    for m in re.finditer(r'\(pin \w+ \w+ \(at ([-\d.]+) ([-\d.]+) (\d+)\) \(length ([\d.]+)\).*?\(number "([^"]+)"',
                         body, re.S):
        pins[m.group(5)] = (float(m.group(1)), float(m.group(2)), int(m.group(3)))
    return body, pins


STOCK = {}  # lib_id -> (sexpr, pins)


def stock(lib, name):
    key = f"{lib}:{name}"
    if key not in STOCK:
        STOCK[key] = lib_symbol(lib, name)
    return key


def stock_for(ref, p):
    if ref.startswith("RT"):
        return stock("Device", "Thermistor_NTC")
    if ref.startswith("R"):
        return stock("Device", "R")
    if ref.startswith("C"):
        return stock("Device", "C")
    if ref.startswith("L"):
        return stock("Device", "L")
    if ref.startswith("D"):
        return stock("Device", "D_Zener")
    if ref.startswith("SW"):
        return stock("Switch", "SW_Push")
    if ref.startswith("TP"):
        return stock("Connector", "TestPoint")
    if ref.startswith("FID"):
        return stock("Mechanical", "Fiducial")
    return None


# ------------------------------------------------------------------ box symbols for ICs and connectors
def pad_key(p):
    m = re.match(r"([A-Z]*)(\d+)$", p)
    return (m.group(1), int(m.group(2))) if m else (p, 0)


def box_symbol(ref, p):
    pads = sorted(set(p["pins"]) | set(p["nc"]), key=pad_key)
    names = NAMES.get(ref, {})

    def pname(pad):
        if pad in names:
            return names[pad]
        if pad in p["nc"]:
            return "NC"
        return p["pins"][pad]

    if ref in SIDES:
        left, right = SIDES[ref]
        right = right + [x for x in pads if x not in left and x not in right]
    elif ref == "U1":  # signals left, power / debug / NC right
        sig = [x for x in pads if x in names and x not in ("5", "6", "7", "26")]
        left = sorted(sig, key=lambda x: names[x])
        right = [x for x in pads if x not in left]
    elif ref.startswith("J") or ref.startswith("E"):
        left, right = pads, []
    else:
        h = (len(pads) + 1) // 2
        left, right = pads[:h], pads[h:]
    nlong = max([len(pname(x)) for x in pads] + [4])
    width = snap(max(10.16, nlong * 1.27 * (2 if left and right else 1) + 5.08), 2 * G)
    rows = max(len(left), len(right), 1)
    height = rows * G + G
    top = snap(height / 2)
    lid = f"Cue:{ref}"
    pins_def, pins = [], {}
    for side, lst in (("L", left), ("R", right)):
        for i, pad in enumerate(lst):
            y = top - G - i * G
            if side == "L":
                x, ang = -width / 2 - G, 0
            else:
                x, ang = width / 2 + G, 180
            pins[pad] = (x, y, ang)
            pins_def.append(
                f'      (pin passive line (at {x:g} {y:g} {ang}) (length {G:g})\n'
                f'        (name "{pname(pad)}" (effects (font (size 1.27 1.27))))\n'
                f'        (number "{pad}" (effects (font (size 1.27 1.27)))))')
    body = (f'  (symbol "{lid}" (pin_names (offset 1.016)) (in_bom yes) (on_board yes)\n'
            f'    (property "Reference" "{re.sub(r"[0-9]+$", "", ref)}" (at 0 {top + 1.27:g} 0) (effects (font (size 1.27 1.27))))\n'
            f'    (property "Value" "{ref}" (at 0 {-top - 1.27:g} 0) (effects (font (size 1.27 1.27))))\n'
            f'    (property "Footprint" "" (at 0 0 0) (effects (font (size 1.27 1.27)) hide))\n'
            f'    (property "Datasheet" "" (at 0 0 0) (effects (font (size 1.27 1.27)) hide))\n'
            f'    (symbol "{ref}_0_1"\n'
            f'      (rectangle (start {-width / 2:g} {top:g}) (end {width / 2:g} {top - height:g})\n'
            f'        (stroke (width 0.254) (type default)) (fill (type background))))\n'
            f'    (symbol "{ref}_1_1"\n' + "\n".join(pins_def) + "\n    )\n  )")
    return lid, body, pins, width, height


# ------------------------------------------------------------------ placement
def footprint_id(p):
    if p["lib"] == C.CUE:
        return f"Cue:{p['fp']}"
    return f"{os.path.basename(p['lib'].rstrip('/')).replace('.pretty', '')}:{p['fp']}"


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


TWO_PIN = ("Device:R", "Device:C", "Device:L", "Device:Thermistor_NTC")


def rot_pin(px, py, ang, rot):
    """Rotate a symbol pin (symbol coords, Y up) by the instance rotation (CCW degrees)."""
    for _ in range(rot // 90):
        px, py, ang = -py, px, (ang + 90) % 360
    return px, py, ang


def build():
    lib_defs, items, blocks_out = {}, [], []
    # columns: power | radio + haptics | sensors + headers
    cols = [[0], [1, 3], [2, 4]]
    col_x = [12.7, 149.86, 284.48]
    col_w = [127.0, 124.0, 120.0]
    for ci, col in enumerate(cols):
        cy = 33.02
        for bi in col:
            title, refs = BLOCKS[bi]
            bx, right = col_x[ci], col_x[ci] + col_w[ci]
            parts = []
            for ref in refs:
                p = C.PARTS[ref]
                lid = stock_for(ref, p)
                rot = 0
                if lid:
                    body, pins = STOCK[lid]
                    lib_defs[lid] = body
                    if lid in TWO_PIN or lid == "Connector:TestPoint":
                        rot = 90
                    pins = {k: rot_pin(*v, rot) for k, v in pins.items()}
                    xs = [v[0] for v in pins.values()] or [0]
                    ys = [v[1] for v in pins.values()] or [0]
                    w, h = max(xs) - min(xs) + 2.54, max(ys) - min(ys) + 5.08
                else:
                    lid, body, pins, bw, bh = box_symbol(ref, p)
                    lib_defs[lid] = body
                    w, h = bw + 2 * G, bh
                longest = max([len(n) for n in p["pins"].values()] + [3])
                parts.append([ref, lid, pins, rot, w, h, longest])
            small = [q for q in parts if q[1] in TWO_PIN or q[1] == "Connector:TestPoint"]
            slab = max([q[6] for q in small] + [3]) * 1.27 + 2.54
            x, y, row_h, stack, placed = bx, cy + 10.16, 0, None, []
            for ref, lid, pins, rot, w, h, longest in parts:
                if lid in TWO_PIN or lid == "Connector:TestPoint":
                    fw, fh = w + 2 * slab, 10.16
                else:
                    lab = longest * 1.27 + 3.81
                    fw, fh = w + 2 * lab, h + 10.16
                if stack and stack[1] + fh <= y + row_h and fw <= stack[2] + 0.01:
                    px, py = stack[0], stack[1]
                    stack[1] += fh
                else:
                    if x + fw > right and placed:
                        x, y, row_h, stack = bx, y + row_h + 2.54, 0, None
                    px, py = x, y
                    stack = [x, y + fh, fw]
                    x += fw + 2.54
                    row_h = max(row_h, fh)
                placed.append((ref, lid, pins, rot, snap(px + fw / 2), snap(py + fh / 2), fw, fh))
            bottom = y + row_h + 2.54
            blocks_out.append((title, bx - 5.08, cy, col_w[ci] + 7.62, bottom - cy))
            cy = bottom + 7.62
            items += placed
    return lib_defs, items, blocks_out


def sch():
    lib_defs, items, blocks = build()
    out = ['(kicad_sch (version 20230121) (generator eeschema)', f'  (uuid {ROOT})', '  (paper "A3")',
           '  (title_block (title "Cue rev A dev board") (date "2026-10-05") (rev "A")',
           '    (company "Cue")', '    (comment 1 "Source: hardware/devboard/devboard_circuit.py")',
           '    (comment 2 "Radio module footprint: see README for status"))',
           '  (lib_symbols']
    for lid in sorted(lib_defs):
        out.append("    " + lib_defs[lid].strip().replace("\n", "\n  "))
    out.append("  )")
    labels = 0
    for ref, lid, pins, rot, cx, cy, fw, fh in items:
        p = C.PARTS[ref]
        bom = "no" if ref.startswith(("FID", "TP", "E")) else "yes"
        props = [("Reference", ref, 0, -fh / 2 + 2.54, False), ("Value", p["value"], 0, fh / 2 - 2.54, False),
                 ("Footprint", footprint_id(p), 0, 0, True), ("Datasheet", "", 0, 0, True),
                 ("MPN", p["mpn"], 0, 0, True)]
        if p["note"]:
            props.append(("Note", p["note"], 0, 0, True))
        if lid in TWO_PIN or lid == "Device:D_Zener":
            props[0] = ("Reference", ref, 0, -3.175, False)
            props[1] = ("Value", p["value"], 0, 3.175, False)
        if lid == "Connector:TestPoint":
            props[0] = ("Reference", ref, 0, -2.54, False)
            props[1] = ("Value", p["value"], 0, 0, True)
        s = [f'  (symbol (lib_id "{lid}") (at {cx:g} {cy:g} {rot}) (unit 1)',
             f'    (in_bom {bom}) (on_board yes) (dnp no) (uuid {uid("sym", ref)})']
        for k, v, dx, dy, hide, *j in props:
            just = f" (justify {j[0]})" if j else ""
            s.append(f'    (property "{k}" "{esc(v)}" (at {cx + dx:g} {cy + dy:g} {rot})'
                     f' (effects (font (size 1.27 1.27)){just}{" hide" if hide else ""}))')
        for pad in pins:
            s.append(f'    (pin "{pad}" (uuid {uid("pin", ref, pad)}))')
        s.append(f'    (instances (project "cue_devboard" (path "/{ROOT}" (reference "{ref}") (unit 1))))')
        s.append("  )")
        out += s
        for pad, (px, py, ang) in pins.items():
            ex, ey = cx + px, cy - py  # symbol Y is up, sheet Y is down
            if pad in p["nc"] or pad not in p["pins"]:
                out.append(f'  (no_connect (at {ex:g} {ey:g}) (uuid {uid("nc", ref, pad)}))')
                continue
            net = p["pins"][pad]
            # pin points into the body along `ang`; the label faces away from the body
            la, just = {0: (180, "right"), 180: (0, "left"), 270: (90, "left"), 90: (270, "right")}[ang]
            out.append(f'  (label "{esc(net)}" (at {ex:g} {ey:g} {la}) (fields_autoplaced)'
                       f' (effects (font (size 1.27 1.27)) (justify {just} bottom)) (uuid {uid("lab", ref, pad)}))')
            labels += 1
    for title, x, y, w, h in blocks:
        out.append(f'  (rectangle (start {x:g} {y:g}) (end {x + w:g} {y + h:g})'
                   f' (stroke (width 0.3) (type dash)) (fill (type none)) (uuid {uid("blk", title)}))')
        out.append(f'  (text "{esc(title)}" (at {x + 2.54:g} {y + 5.08:g} 0)'
                   f' (effects (font (size 2.54 2.54) bold) (justify left bottom)) (uuid {uid("t", title)}))')
    ny = max(b[2] + b[4] for b in blocks if b[1] < 100) + 6.35
    for i, n in enumerate(NOTES):
        out.append(f'  (text "{esc(n)}" (at 12.7 {ny + i * 3.81:g} 0)'
                   f' (effects (font (size 1.5 1.5)) (justify left bottom)) (uuid {uid("note", i)}))')
    out.append('  (sheet_instances (path "/" (page "1")))')
    out.append(")")
    open(OUT, "w").write("\n".join(out) + "\n")
    pro = OUT.replace(".kicad_sch", ".kicad_pro")
    if not os.path.exists(pro):
        open(pro, "w").write('{"meta": {"filename": "cue_devboard.kicad_pro", "version": 1}}\n')
    return len(items), labels


if __name__ == "__main__":
    n, l = sch()
    print(f"wrote {OUT}: {n} symbols, {l} net labels")
